In [3]:
import argparse

import dgl
import networkx as nx
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F

from nodeclassification import *
from models import NodeClassification

import pdb
import random

In [4]:
graphs, cov = synthetic_dataset(2, sample_cov)

In [6]:
batched_graph = dgl.batch(graphs)
labels = get_labels(batched_graph)
feats, mask = get_normalized_features(batched_graph)

In [29]:
prior = feats[mask]

In [31]:
prior[1].log()

tensor([-1.6341, -1.3157, -0.6225])

In [ ]:
def h_star(g, mask, cov, prior, num=NUM_TEST_PER_GRAPH, logits=True):
    H = get_labels(g)
    out = torch.stack([H[g.successors(nid)].mm(cov[i//num]).log().sum(0) + prior[i].log() for i, nid in enumerate(mask)])
    if logits: return out
    return out.softmax(1)

In [23]:
H[batched_graph.successors(14)].mm(cov[0]).log().sum(0) + 

tensor([-12.0355,  -8.3995, -18.5407])

In [26]:
feats[14]

tensor([0.1951, 0.2683, 0.5366])

In [18]:
H[batched_graph.successors(14)].

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

In [16]:
cov[0]

tensor([[0.7060, 0.1110, 0.0900],
        [0.1110, 0.6970, 0.1040],
        [0.0900, 0.1040, 0.7030]])

In [9]:
H = get_labels(batched_graph)

In [12]:
mask

tensor([14, 17, 24, 27, 29, 42, 48, 49, 69, 84])

In [7]:
h_star(batched_graph, mask, cov)

tensor([[-12.0355,  -8.3995, -18.5407],
        [-15.8070,  -6.3316, -12.0216],
        [-36.5344, -34.8380, -18.2427],
        [-35.9095, -32.0481,  -7.1969],
        [-41.0735, -38.7730, -10.3097],
        [-14.6495, -26.7846, -28.2094],
        [ -9.2397, -23.5140, -16.7377],
        [-21.4507, -32.0307, -31.3362],
        [-30.6438, -13.4954, -32.0339],
        [-29.5342, -34.0567,  -6.6967]])